apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z09010031B5WO10NMKAAD
          region: eu-central-1
      selector:
        dnsZones:
          - dev.nilahomar.com

# file changed
