apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default  # Change this if needed
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  POSTGRES_DB: cG9zdGdyZXM=  # Base64-encoded value of 'postgres'
