name: Deploy Kustomize to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'manifests/**.yaml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.get_dirs.outputs.changed_dirs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed directories
        id: get_dirs
        run: |
          # Get changed files in the manifests directory
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'manifests/**.yaml')

          # Extract unique directories
          if [[ -z "$changed_files" ]]; then
            echo "No manifests files were modified. Skipping apply."
            echo "changed_dirs=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          changed_dirs=$(echo "$changed_files" | awk -F'/' '{print $1"/"$2}' | sort -u | jq -R -s -c 'split("\n")[:-1]')

          # Store directories as an output variable
          echo "changed_dirs=$changed_dirs" >> $GITHUB_ENV
          echo "changed_dirs=$changed_dirs" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to EKS
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.changed_dirs != '' && needs.detect-changes.outputs.changed_dirs != '[]' && contains(needs.detect-changes.outputs.changed_dirs, '[') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.detect-changes.outputs.changed_dirs) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name dev-01 --region ${{ secrets.AWS_REGION }}

      - name: Install Kustomize
        run: |
          KUSTOMIZE_VERSION=v5.6.0
          curl -sLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
          tar -xzf kustomize.tar.gz
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

      - name: Deploy Kustomize Manifests
        working-directory: ${{ matrix.dir }}
        run: |
          kustomize build . | kubectl apply -f -
